import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { api } from '../lib/api.js';
import { ArrowLeft, Download, Loader2, Target, Activity, AlertTriangle, ListChecks, Clock, Shield } from 'lucide-react';

function Section({ icon: Icon, title, children, color = 'text-primary bg-primary/15' }) { return <div className="card mb-6"><div className="flex items-center gap-2 mb-3"><div className={'rounded-lg p-1.5 ' + color}><Icon size={16} /></div><h2 className="font-headline text-xl font-semibold text-on-surface">{title}</h2></div>{children}</div>; }
function ScoreCard({ label, value, suffix = '' }) { return <div className="rounded-2xl bg-surface-container-high p-5 text-center"><p className="text-4xl font-bold text-primary">{value}{suffix}</p><p className="mt-2 text-xs uppercase tracking-widest text-on-surface-variant">{label}</p></div>; }

export default function MetasExecucaoReportPage() {
  const { id } = useParams(); const navigate = useNavigate();
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [downloading,setDownloading]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{(async()=>{try{setData(await api.get('/assessments/'+id+'/report'));}catch(e){setError(e.message);}finally{setLoading(false);}})();},[id]);
  const downloadPDF = async () => { setDownloading(true); try { const token = api.getToken(); const response = await fetch('/api/reports/' + id + '/pdf', { headers: { Authorization: 'Bearer ' + token } }); if (!response.ok) { const err = await response.json().catch(() => ({})); throw new Error(err.error || 'Erro ao gerar PDF'); } const blob = await response.blob(); const url = window.URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'mapa-de-metas-e-execucao.pdf'; document.body.appendChild(link); link.click(); link.remove(); window.URL.revokeObjectURL(url); } catch (e) { alert('Erro ao baixar PDF: ' + e.message); } finally { setDownloading(false); } };
  if(loading) return <div className="flex h-screen items-center justify-center bg-surface"><Loader2 className="h-8 w-8 animate-spin text-primary"/></div>;
  if(error) return <div className="p-8"><div className="card text-center py-12"><p className="text-red-400">{error}</p><button onClick={()=>navigate(-1)} className="btn-secondary mt-4 gap-2"><ArrowLeft size={16}/>Voltar</button></div></div>;
  const narrative=data?.report?.narrative||{}; const scores=data?.scoresRaw||{}; const diagnosis=scores.diagnosis||{}; const userName=data?.userName||'Usuário';
  return <div className="min-h-screen bg-surface"><div className="mx-auto max-w-4xl px-4 py-8">
    <div className="flex items-center justify-between mb-6"><button onClick={()=>navigate(-1)} className="btn-secondary gap-1"><ArrowLeft size={16}/>Voltar</button><button onClick={downloadPDF} disabled={downloading} className="btn-primary gap-2">{downloading?<Loader2 size={16} className="animate-spin"/>:<Download size={16}/>}Baixar PDF</button></div>
    <div className="card mb-6 text-center"><p className="text-xs font-medium uppercase tracking-widest text-on-surface-variant/50 mb-2">Mapa de Metas e Execução</p><h1 className="font-headline text-2xl font-bold text-on-surface mb-1">{userName}</h1><p className="text-sm text-on-surface-variant">{narrative.metaRefinada || scores.goal?.raw}</p><div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4"><ScoreCard label="Prontidão" value={diagnosis.readinessScore ?? 0}/><ScoreCard label="Clareza" value={diagnosis.clarityScore ?? 0}/><ScoreCard label="Estado atual" value={diagnosis.currentState ?? 0} suffix="/10"/></div></div>
    {narrative.resumoExecutivo && <div className="card mb-6"><h2 className="font-headline text-xl font-semibold text-on-surface mb-3">Resumo Executivo</h2><p className="text-sm text-on-surface-variant leading-relaxed">{narrative.resumoExecutivo}</p></div>}
    {narrative.leituraDoMomento && <Section icon={Activity} title="Leitura do Momento"><p className="text-sm text-on-surface-variant leading-relaxed whitespace-pre-line">{narrative.leituraDoMomento}</p></Section>}
    {narrative.diagnosticoDeExecucao && <Section icon={Target} title="Diagnóstico de Execução"><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{Object.entries(narrative.diagnosticoDeExecucao).map(([k,v])=><div key={k} className="rounded-xl bg-surface-container-high/50 p-4"><p className="text-xs font-bold uppercase tracking-widest text-primary">{k.replaceAll('_',' ')}</p><p className="mt-1 text-sm text-on-surface-variant">{v}</p></div>)}</div></Section>}
    {narrative.metaSMART && <Section icon={Target} title="Meta SMART"><div className="space-y-3">{Object.entries(narrative.metaSMART).map(([k,v])=><div key={k} className="rounded-xl bg-primary/5 border border-primary/15 px-4 py-3"><p className="text-xs font-bold uppercase tracking-widest text-primary">{k}</p><p className="mt-1 text-sm text-on-surface-variant">{v}</p></div>)}</div></Section>}
    {Array.isArray(narrative.plano30Dias) && <Section icon={ListChecks} title="Plano de 30 dias"><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{narrative.plano30Dias.map((week,i)=><div key={i} className="rounded-xl bg-surface-container-high/50 p-4"><p className="text-primary text-xs font-bold uppercase tracking-widest">Semana {week.semana}</p><p className="font-semibold text-on-surface mt-1">{week.foco}</p><ul className="mt-3 space-y-1">{(week.acoes||[]).map((a,j)=><li key={j} className="text-xs text-on-surface-variant">• {a}</li>)}</ul><p className="text-xs text-emerald-400 mt-3">Indicador: {week.indicador}</p></div>)}</div></Section>}
    {Array.isArray(narrative.primeiras24Horas) && <Section icon={Clock} title="Primeiras 24 horas" color="text-emerald-400 bg-emerald-500/15"><div className="space-y-2">{narrative.primeiras24Horas.map((a,i)=><div key={i} className="rounded-xl bg-emerald-500/5 border border-emerald-500/15 px-4 py-3 text-sm text-on-surface-variant">{i+1}. {a}</div>)}</div></Section>}
    {narrative.rotinaMinima && <Section icon={ListChecks} title="Rotina mínima"><p className="text-sm text-on-surface-variant leading-relaxed">{narrative.rotinaMinima}</p></Section>}
    {Array.isArray(narrative.planoAntiSabotagem) && <Section icon={Shield} title="Plano anti-sabotagem" color="text-amber-400 bg-amber-500/15"><div className="space-y-3">{narrative.planoAntiSabotagem.map((item,i)=><div key={i} className="rounded-xl bg-amber-500/5 border border-amber-500/15 px-4 py-3"><p className="text-sm font-semibold text-on-surface">{item.obstaculo}</p><p className="text-xs text-on-surface-variant mt-1">{item.respostaPratica}</p></div>)}</div></Section>}
    {narrative.fraseFinal && <div className="card mb-6 text-center"><p className="font-headline text-xl text-primary italic">{narrative.fraseFinal}</p></div>}
    <div className="text-center text-xs text-on-surface-variant/40 py-4">Vanessa Rocha — Mapa de Metas e Execução</div>
  </div></div>;
}
