import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { api } from '../lib/api.js';
import { ArrowLeft, Download, Loader2, Shield, Zap, Brain, Wrench, Clock, AlertTriangle } from 'lucide-react';

function Section({ icon: Icon, title, children, color = 'text-primary bg-primary/15' }) { return <div className="card mb-6"><div className="flex items-center gap-2 mb-3"><div className={'rounded-lg p-1.5 ' + color}><Icon size={16} /></div><h2 className="font-headline text-xl font-semibold text-on-surface">{title}</h2></div>{children}</div>; }
function ScoreBar({ item }) { return <div className="rounded-xl bg-surface-container-high/50 px-4 py-3"><div className="mb-1 flex justify-between"><span className="text-sm font-semibold text-on-surface">{item.name}</span><span className="text-xs font-bold text-primary">{item.score}</span></div><div className="h-2 rounded-full bg-surface-container-highest"><div className="h-full rounded-full bg-primary" style={{ width: item.score + '%' }} /></div></div>; }

export default function SabotadoresReportPage() {
  const { id } = useParams(); const navigate = useNavigate();
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [downloading,setDownloading]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{(async()=>{try{setData(await api.get('/assessments/'+id+'/report'));}catch(e){setError(e.message);}finally{setLoading(false);}})();},[id]);
  const downloadPDF = async () => { setDownloading(true); try { const token = api.getToken(); const response = await fetch('/api/reports/' + id + '/pdf', { headers: { Authorization: 'Bearer ' + token } }); if (!response.ok) { const err = await response.json().catch(() => ({})); throw new Error(err.error || 'Erro ao gerar PDF'); } const blob = await response.blob(); const url = window.URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'mapa-de-sabotadores-internos.pdf'; document.body.appendChild(link); link.click(); link.remove(); window.URL.revokeObjectURL(url); } catch (e) { alert('Erro ao baixar PDF: ' + e.message); } finally { setDownloading(false); } };
  if(loading) return <div className="flex h-screen items-center justify-center bg-surface"><Loader2 className="h-8 w-8 animate-spin text-primary"/></div>;
  if(error) return <div className="p-8"><div className="card text-center py-12"><p className="text-red-400">{error}</p><button onClick={()=>navigate(-1)} className="btn-secondary mt-4 gap-2"><ArrowLeft size={16}/>Voltar</button></div></div>;
  const narrative=data?.report?.narrative||{}; const scores=data?.scoresRaw||{}; const ranking=scores.ranking||[]; const userName=data?.userName||'Usuário';
  return <div className="min-h-screen bg-surface"><div className="mx-auto max-w-4xl px-4 py-8">
    <div className="flex items-center justify-between mb-6"><button onClick={()=>navigate(-1)} className="btn-secondary gap-1"><ArrowLeft size={16}/>Voltar</button><button onClick={downloadPDF} disabled={downloading} className="btn-primary gap-2">{downloading?<Loader2 size={16} className="animate-spin"/>:<Download size={16}/>}Baixar PDF</button></div>
    <div className="card mb-6 text-center"><p className="text-xs font-medium uppercase tracking-widest text-on-surface-variant/50 mb-2">Mapa de Sabotadores Internos</p><h1 className="font-headline text-2xl font-bold text-on-surface mb-1">{userName}</h1><p className="text-sm text-on-surface-variant">Padrões automáticos, gatilhos e plano de neutralização</p><div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4"><div className="rounded-2xl bg-surface-container-high p-5"><p className="text-xs uppercase tracking-widest text-on-surface-variant">Principal</p><p className="mt-2 text-xl font-bold text-primary">{scores.primarySabotager?.name}</p></div><div className="rounded-2xl bg-surface-container-high p-5"><p className="text-xs uppercase tracking-widest text-on-surface-variant">Secundário</p><p className="mt-2 text-xl font-bold text-primary">{scores.secondarySabotager?.name}</p></div><div className="rounded-2xl bg-surface-container-high p-5"><p className="text-xs uppercase tracking-widest text-on-surface-variant">Impacto</p><p className="mt-2 text-xl font-bold text-primary">{scores.impact?.score}/10</p></div></div></div>
    <Section icon={Shield} title="Ranking de sabotadores"><div className="space-y-3">{ranking.slice(0,5).map(item=><ScoreBar key={item.id} item={item}/>)}</div></Section>
    {narrative.resumoExecutivo && <div className="card mb-6"><h2 className="font-headline text-xl font-semibold text-on-surface mb-3">Resumo Executivo</h2><p className="text-sm text-on-surface-variant leading-relaxed">{narrative.resumoExecutivo}</p></div>}
    {narrative.sabotadorPrincipal && <Section icon={AlertTriangle} title="Sabotador principal" color="text-amber-400 bg-amber-500/15"><div className="space-y-3"><p className="text-lg font-semibold text-on-surface">{narrative.sabotadorPrincipal.nome}</p><p className="text-sm text-on-surface-variant leading-relaxed">{narrative.sabotadorPrincipal.leitura}</p><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><div className="rounded-xl bg-emerald-500/5 border border-emerald-500/15 p-3"><p className="text-xs font-bold text-emerald-400 uppercase tracking-widest">Como protege</p><p className="mt-1 text-xs text-on-surface-variant">{narrative.sabotadorPrincipal.comoProtege}</p></div><div className="rounded-xl bg-amber-500/5 border border-amber-500/15 p-3"><p className="text-xs font-bold text-amber-400 uppercase tracking-widest">Como sabota</p><p className="mt-1 text-xs text-on-surface-variant">{narrative.sabotadorPrincipal.comoSabota}</p></div></div></div></Section>}
    {narrative.cicloDeSabotagem && <Section icon={Brain} title="Ciclo de sabotagem"><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{Object.entries(narrative.cicloDeSabotagem).map(([k,v])=><div key={k} className="rounded-xl bg-surface-container-high/50 p-4"><p className="text-xs font-bold uppercase tracking-widest text-primary">{k}</p><p className="mt-1 text-sm text-on-surface-variant">{v}</p></div>)}</div></Section>}
    {Array.isArray(narrative.mapaDeGatilhos) && <Section icon={Zap} title="Mapa de gatilhos"><div className="space-y-3">{narrative.mapaDeGatilhos.map((item,i)=><div key={i} className="rounded-xl bg-surface-container-high/50 px-4 py-3"><p className="text-sm font-semibold text-on-surface">{item.gatilho}</p><p className="text-xs text-on-surface-variant mt-1">{item.comoAparece}</p><p className="text-xs text-primary mt-2">Resposta consciente: {item.respostaConsciente}</p></div>)}</div></Section>}
    {Array.isArray(narrative.planoDeNeutralizacao) && <Section icon={Wrench} title="Plano de neutralização"><div className="space-y-3">{narrative.planoDeNeutralizacao.map((item,i)=><div key={i} className="rounded-xl bg-primary/5 border border-primary/15 px-4 py-3"><p className="text-sm font-semibold text-on-surface">{item.situacao}</p><p className="text-xs text-on-surface-variant mt-1">Antídoto: {item.antidoto}</p><p className="text-xs text-primary mt-2">Ação: {item.acaoPratica}</p></div>)}</div></Section>}
    {Array.isArray(narrative.primeiras24Horas) && <Section icon={Clock} title="Primeiras 24 horas" color="text-emerald-400 bg-emerald-500/15"><div className="space-y-2">{narrative.primeiras24Horas.map((a,i)=><div key={i} className="rounded-xl bg-emerald-500/5 border border-emerald-500/15 px-4 py-3 text-sm text-on-surface-variant">{i+1}. {a}</div>)}</div></Section>}
    {narrative.roteiroDeInterrupcao && <div className="card mb-6 text-center"><p className="text-xs font-bold uppercase tracking-widest text-primary mb-2">Roteiro de interrupção</p><p className="font-headline text-xl text-on-surface italic">“{narrative.roteiroDeInterrupcao}”</p></div>}
    {Array.isArray(narrative.plano7Dias) && <Section icon={Wrench} title="Plano de 7 dias"><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{narrative.plano7Dias.map((d,i)=><div key={i} className="rounded-xl bg-surface-container-high/50 p-4"><p className="text-primary text-xs font-bold uppercase tracking-widest">Dia {d.dia}</p><p className="mt-1 text-sm text-on-surface-variant">{d.acao}</p><p className="mt-2 text-xs text-emerald-400">Indicador: {d.indicador}</p></div>)}</div></Section>}
    {narrative.fraseFinal && <div className="card mb-6 text-center"><p className="font-headline text-xl text-primary italic">{narrative.fraseFinal}</p></div>}
    <div className="text-center text-xs text-on-surface-variant/40 py-4">Vanessa Rocha — Mapa de Sabotadores Internos</div>
  </div></div>;
}
