import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { api } from '../lib/api.js';
import { ArrowLeft, Download, Loader2, Compass, AlertTriangle, Heart, Target, Coins, Sparkles, Layers, GitBranch, CheckCircle2 } from 'lucide-react';

const dimensionOrder = ['identidade', 'familia_relacionamentos', 'crescimento', 'contribuicao', 'prosperidade', 'espiritualidade_proposito'];
const dimensionColors = { identidade: '#E63946', familia_relacionamentos: '#ec4899', crescimento: '#4c6ef5', contribuicao: '#2A9D8F', prosperidade: '#F4A261', espiritualidade_proposito: '#d4a853' };

function Section({ icon: Icon, title, children, color = 'text-primary bg-primary/15' }) { return <div className="card mb-6"><div className="flex items-center gap-2 mb-3"><div className={'rounded-lg p-1.5 ' + color}><Icon size={16} /></div><h2 className="font-headline text-xl font-semibold text-on-surface">{title}</h2></div>{children}</div>; }
function nameOf(id, dimensions) { return dimensions[id]?.name || id?.replaceAll('_', ' ') || ''; }
function RankingCard({ title, icon: Icon, items, dimensions, empty = 'Sem dados suficientes.' }) { return <div className="rounded-2xl border border-outline-variant/15 bg-surface-container-low p-4"><div className="mb-3 flex items-center gap-2"><Icon size={15} className="text-primary" /><h3 className="font-headline text-sm font-semibold text-on-surface">{title}</h3></div><div className="space-y-2">{(items || []).filter(i => (i.score ?? i.count ?? 0) > 0).slice(0, 6).length === 0 ? <p className="text-xs text-on-surface-variant">{empty}</p> : (items || []).filter(i => (i.score ?? i.count ?? 0) > 0).slice(0, 6).map((item, index) => { const color = dimensionColors[item.id] || '#d4a853'; const value = item.score ?? item.count ?? 0; const pct = item.score !== undefined ? item.score : Math.min(100, value * 20); return <div key={item.id} className="rounded-xl bg-surface-container-high/50 px-3 py-2"><div className="mb-1 flex items-center justify-between gap-2"><span className="text-xs font-semibold text-on-surface">{index + 1}. {item.name || nameOf(item.id, dimensions)}</span><span className="text-xs font-bold" style={{ color }}>{value}</span></div><div className="h-1.5 rounded-full bg-surface-container-highest"><div className="h-full rounded-full" style={{ width: pct + '%', backgroundColor: color }} /></div></div>; })}</div></div>; }

export default function ValoresPessoaisReportPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [downloading, setDownloading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { (async () => { try { setData(await api.get('/assessments/' + id + '/report')); } catch (e) { setError(e.message); } finally { setLoading(false); } })(); }, [id]);
  const downloadPDF = async () => { setDownloading(true); try { const token = api.getToken(); const response = await fetch('/api/reports/' + id + '/pdf', { headers: { Authorization: 'Bearer ' + token } }); if (!response.ok) { const err = await response.json().catch(() => ({})); throw new Error(err.error || 'Erro ao gerar PDF'); } const blob = await response.blob(); const url = window.URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'mapa-de-valores-pessoais.pdf'; document.body.appendChild(link); link.click(); link.remove(); window.URL.revokeObjectURL(url); } catch (e) { alert('Erro ao baixar PDF: ' + e.message); } finally { setDownloading(false); } };
  if (loading) return <div className="flex h-screen items-center justify-center bg-surface"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;
  if (error) return <div className="p-8"><div className="card text-center py-12"><p className="text-red-400">{error}</p><button onClick={() => navigate(-1)} className="btn-secondary mt-4 gap-2"><ArrowLeft size={16} />Voltar</button></div></div>;
  const narrative = data?.report?.narrative || {}; const scoresRaw = data?.scoresRaw || {}; const dimensions = scoresRaw.dimensions || {}; const userName = data?.userName || 'Usuário'; const coherence = scoresRaw.coherenceMap || narrative.mapaDeCoerencia || {};
  return <div className="min-h-screen bg-surface"><div className="mx-auto max-w-4xl px-4 py-8">
    <div className="flex items-center justify-between mb-6"><button onClick={() => navigate(-1)} className="btn-secondary gap-1"><ArrowLeft size={16} />Voltar</button><button onClick={downloadPDF} disabled={downloading} className="btn-primary gap-2">{downloading ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}Baixar PDF</button></div>
    <div className="card mb-6 text-center"><p className="text-xs font-medium uppercase tracking-widest text-on-surface-variant/50 mb-2">Mapa de Valores Pessoais</p><h1 className="font-headline text-2xl font-bold text-on-surface mb-1">{userName}</h1><p className="text-sm text-on-surface-variant">Hierarquia, coerência e valores sob pressão</p><div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4 text-left"><RankingCard title="Valores reconhecidos" icon={Compass} items={scoresRaw.hierarchy?.declared} dimensions={dimensions} /><RankingCard title="Valores priorizados" icon={Layers} items={scoresRaw.hierarchy?.prioritized} dimensions={dimensions} /><RankingCard title="Valores sob pressão" icon={GitBranch} items={scoresRaw.hierarchy?.underPressure} dimensions={dimensions} /></div></div>
    <div className="card mb-6"><h2 className="font-headline text-xl font-semibold text-on-surface mb-4">Mapa de Coerência</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-center"><div className="text-center rounded-2xl bg-surface-container-high p-6"><p className="text-5xl font-bold text-primary">{coherence.score ?? 0}</p><p className="text-xs text-on-surface-variant uppercase tracking-widest mt-2">Coerência</p></div><div className="md:col-span-2"><p className="text-sm text-on-surface-variant leading-relaxed">{narrative.mapaDeCoerencia?.leitura || 'Este indicador compara valores reconhecidos, priorizados e acionados sob pressão.'}</p><div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-3"><div className="rounded-xl bg-emerald-500/5 border border-emerald-500/15 p-3"><p className="text-xs font-bold text-emerald-400 uppercase tracking-widest mb-2">Coerências</p>{(narrative.mapaDeCoerencia?.pontosDeCoerencia || coherence.coherent || []).slice(0,3).map((v,i)=><p key={i} className="text-xs text-on-surface-variant mb-1">• {typeof v === 'string' ? nameOf(v, dimensions) : v}</p>)}</div><div className="rounded-xl bg-amber-500/5 border border-amber-500/15 p-3"><p className="text-xs font-bold text-amber-400 uppercase tracking-widest mb-2">Desalinhamentos</p>{(narrative.mapaDeCoerencia?.pontosDeDesalinhamento || coherence.declaredButNotChosen || []).slice(0,3).map((v,i)=><p key={i} className="text-xs text-on-surface-variant mb-1">• {typeof v === 'string' ? nameOf(v, dimensions) : v}</p>)}</div></div></div></div></div>
    {narrative.resumoExecutivo && <div className="card mb-6"><h2 className="font-headline text-xl font-semibold text-on-surface mb-3">Resumo Executivo</h2><p className="text-sm text-on-surface-variant leading-relaxed">{narrative.resumoExecutivo}</p></div>}
    {narrative.leituraCentral && <div className="card mb-6"><h2 className="font-headline text-xl font-semibold text-on-surface mb-3">Leitura Central</h2><p className="text-sm text-on-surface-variant leading-relaxed whitespace-pre-line">{narrative.leituraCentral}</p></div>}
    {Array.isArray(narrative.hierarquiaDeValores) && <Section icon={Compass} title="Sua Hierarquia de Valores"><div className="space-y-3">{narrative.hierarquiaDeValores.map((item, i) => <div key={i} className="rounded-xl bg-surface-container-high/50 px-4 py-3"><div className="flex items-center justify-between mb-1"><p className="text-sm font-semibold text-on-surface">{item.posicao}. {item.valor}</p><span className="text-xs font-bold text-primary uppercase">{item.base}</span></div><p className="text-xs text-on-surface-variant">{item.leitura}</p></div>)}</div></Section>}
    {Array.isArray(narrative.valoresSobPressao) && <Section icon={GitBranch} title="Valores sob Pressão" color="text-[#F4A261] bg-[#F4A261]/15"><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{narrative.valoresSobPressao.map((item, i) => <div key={i} className="rounded-xl bg-surface-container-high/50 px-4 py-3"><p className="text-xs font-bold uppercase tracking-widest text-primary">{item.contexto}</p><p className="mt-1 text-sm font-semibold text-on-surface">{item.valorAcionado}</p><p className="mt-2 text-xs text-on-surface-variant">{item.leitura}</p>{item.cuidado && <p className="mt-2 text-xs text-amber-400">Cuidado: {item.cuidado}</p>}</div>)}</div></Section>}
    {Array.isArray(narrative.tensoesInternas) && <Section icon={AlertTriangle} title="Tensões Internas" color="text-amber-400 bg-amber-500/15"><div className="space-y-3">{narrative.tensoesInternas.map((item, i) => <div key={i} className="rounded-xl bg-amber-500/5 border border-amber-500/15 px-4 py-3"><div className="flex items-center justify-between mb-1"><p className="text-sm font-semibold text-on-surface">{item.tensao}</p><span className="text-xs font-bold text-amber-400 uppercase">{item.severidade}</span></div><p className="text-xs text-on-surface-variant mt-1">{item.leitura}</p><p className="text-xs text-amber-400 mt-2">Como aparece: {item.comoAparece}</p><p className="text-xs text-primary mt-2">Ação: {item.acaoDeAlinhamento}</p></div>)}</div></Section>}
    {Array.isArray(narrative.sinergias) && <Section icon={Sparkles} title="Sinergias" color="text-primary bg-primary/15"><div className="space-y-3">{narrative.sinergias.map((item, i) => <div key={i} className="rounded-xl bg-primary/5 border border-primary/15 px-4 py-3"><div className="flex items-center justify-between mb-1"><p className="text-sm font-semibold text-on-surface">{item.sinergia}</p><span className="text-xs font-bold text-primary uppercase">{item.forca}</span></div><p className="text-xs text-on-surface-variant mt-1">{item.leitura}</p><p className="text-xs text-primary mt-2">Como potencializar: {item.comoPotencializar}</p></div>)}</div></Section>}
    {narrative.impactoNasDecisoes && <Section icon={CheckCircle2} title="Impacto nas Decisões"><p className="text-sm text-on-surface-variant leading-relaxed whitespace-pre-line">{narrative.impactoNasDecisoes}</p></Section>}
    {narrative.impactoNosRelacionamentos && <Section icon={Heart} title="Impacto nos Relacionamentos" color="text-pink-400 bg-pink-500/15"><p className="text-sm text-on-surface-variant leading-relaxed whitespace-pre-line">{narrative.impactoNosRelacionamentos}</p></Section>}
    {narrative.impactoNaProsperidade && <Section icon={Coins} title="Impacto na Prosperidade" color="text-[#F4A261] bg-[#F4A261]/15"><p className="text-sm text-on-surface-variant leading-relaxed whitespace-pre-line">{narrative.impactoNaProsperidade}</p></Section>}
    {narrative.impactoNoProposito && <Section icon={Sparkles} title="Impacto no Propósito"><p className="text-sm text-on-surface-variant leading-relaxed whitespace-pre-line">{narrative.impactoNoProposito}</p></Section>}
    {Array.isArray(narrative.planoDeAlinhamento30Dias) && <Section icon={Target} title="Plano de Alinhamento — 30 dias"><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{narrative.planoDeAlinhamento30Dias.map((week, i) => <div key={i} className="rounded-xl bg-surface-container-high/50 p-4"><p className="text-primary text-xs font-bold uppercase tracking-widest">Semana {week.semana}</p><p className="font-semibold text-on-surface mt-1">{week.foco}</p><p className="text-xs text-on-surface-variant mt-2">{week.pratica}</p><p className="text-xs text-emerald-400 mt-2">Indicador: {week.indicador}</p></div>)}</div></Section>}
    {narrative.fraseFinal && <div className="card mb-6 text-center"><p className="font-headline text-xl text-primary italic">{narrative.fraseFinal}</p></div>}
    <div className="text-center text-xs text-on-surface-variant/40 py-4"><p>Vanessa Rocha — Mapa de Valores Pessoais</p><p className="mt-1">Gerado em {new Date(data.report.generatedAt).toLocaleDateString('pt-BR')}</p></div>
  </div></div>;
}
